name: Build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Install vcpkg
        run: |
          git clone https://github.com/microsoft/vcpkg.git deps/vcpkg
          deps/vcpkg/bootstrap-vcpkg.bat

      - name: Configure CMake
        run: cmake --preset msvc-x64

      - name: Build Release
        run: cmake --build --preset win64-msvc-release

      - name: Upload executable
        uses: actions/upload-artifact@v4
        with:
          name: FiveMapper-exe
          path: build/msvc-x64/Release/FiveMapper.exe
